version: "2"

services:
  jellyfin:
    image: jellyfin/jellyfin:10.9.11
    volumes:
      - ./videos:/media/videos
      - ./output/:/config/plugins/HappyMovie/
      - ./release/:/var/lib/jellyfin/plugins/
    ports:
      - 8896:8096
