version: "2"

services:
  jellyfin:
    image: jellyfin/jellyfin:10.8.4
    volumes:
      - ./videos:/media/videos
      - ./output/:/config/plugins/HappyMovie/
    ports:
      - 127.0.0.1:8896:8096
